version: '3'

services:
  back-end:
    build:
      context: ./back-end
    ports:
      - "5252:5252"
    depends_on:
    - proxy

  front-end:
    build:
      context: ./front-end
    ports:
      - "9000:80"
    depends_on:
      - back-end

  proxy:
    build:
      context: ./proxy
    ports:
      - "80:80"
    depends_on:
      - front-end
      - back-end
