version: '3'

services:
  backend:
    build:
      context: ./back-end
    ports:
      - "5252:5252"
  frontend:
    build:
      context: ./front-end
    ports:
      - "9000:9000"
    depends_on:
      - backend
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
